name: Sync FROM Hugging Face Space

on:
  schedule:
    # Mengatur bot untuk otomatis memeriksa HF setiap 10 menit
    - cron: '*/10 * * * *'
  workflow_dispatch: # Kolom ini membuat kamu bisa klik tombol "Run workflow" secara manual di web GitHub

jobs:
  sync-from-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Git Config
        run: |
          git config --global user.name "hf-sync-bot"
          git config --global user.email "bot@huggingface.co"

      - name: Pull and Merge from HF Space
        run: |
          git remote add hf https://huggingface.co/spaces/thrdchld/ghostwriter
          git fetch hf
          
          # Gunakan strategi merge 'theirs' agar jika ada file dihapus di HF, di GitHub juga ikut terhapus
          git merge hf/main --allow-unrelated-histories -X theirs -m "Sync: Otomatis menarik perubahan dari HF Space [skip ci]"
          
          git push origin main